name: Build Scrapper Windows EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Verify JAR
        run: |
          dir dist
          java -jar dist/scrapper.jar --version  # Optional: test JAR (adjust if no --version)
        shell: cmd
      - name: Run jpackage for Windows
        run: |
          jpackage ^
            --name Scrapper ^
            --input dist ^
            --main-jar scrapper.jar ^
            --main-class com.desktop.Launcher ^
            --type exe ^
            --dest out/dist ^
            --win-console
        shell: cmd
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scrapper-Windows
          path: out/dist/Scrapper.exe
