name: Build Scrapper Windows EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Verify JAR Presence
        run: |
          dir dist
          if not exist dist\scrapper.jar (echo JAR not found && exit /b 1)
        shell: cmd
      - name: Build Custom JRE with jlink
        run: |
          mkdir jre
          jlink ^
            --output jre ^
            --add-modules com.desktop.scrapper,java.base,java.desktop,javafx.controls,javafx.fxml,org.jsoup,org.slf4j,java.net.http,org.apache.commons.io ^
            --compress=2 ^
            --no-header-files ^
            --no-man-pages ^
            --strip-debug
        shell: cmd
      - name: Run jpackage for Windows
        run: |
          mkdir out\dist
          jpackage ^
            --verbose ^
            --name Scrapper ^
            --input dist ^
            --main-jar scrapper.jar ^
            --main-class com.desktop.Launcher ^
            --type app-image ^
            --dest out/dist ^
            --runtime-image jre ^
            --win-console
        shell: cmd
      - name: Check Output Directory
        run: |
          dir out\dist
        shell: cmd
      - name: Package into Single EXE
        run: |
          copy out\dist\Scrapper\bin\Scrapper.exe out\dist\Scrapper.exe
        shell: cmd
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scrapper-Windows
          path: out/dist/Scrapper.exe